title: "Exercise 2: OOP với bài toán chuẩn bị trang phục"
summary: Giải quyết bài toán OOP để trừu tượng hóa việc chuẩn bị trang phục theo đa dạng phong cách
author: nmhillusion
date: 2024-10-20
bannerLink: "https://nmhillusion.github.io/n2code-owl/oop/exercise-2/summer-outfit-ideas.jpg"
