title: "Post 1: Value of fields between parent and children with access modifiers"
summary: Trình bày sự liên qua và sự kế thừa của các fields giữa lớp cha và lớp con trong lập trình hướng đối tượng
author: nmhillusion
date: 2024-11-02
bannerLink: "https://nmhillusion.github.io/n2code-owl/oop/post-1--value-of-fields-between-parent-and-children/hierarchy.png"
