title: "Exercise 1: OOP với các phép tính cơ bản"
summary: Giải quyết bài toán OOP để trừu tượng hóa các phép tính cơ bản
author: nmhillusion
date: 2024-10-27
bannerLink: "https://nmhillusion.github.io/n2code-owl/oop/exercise-1/math-operators.jpg"
